"""add_user_profile_fields

Revision ID: 809c063ac489
Revises: b8e014bf7f15
Create Date: 2026-09-19 19:21:51.261034

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "809c063ac489"
down_revision: str | Sequence[str] | None = "b8e014bf7f15"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("users", sa.Column("full_name", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("phone_number", sa.String(length=32), nullable=True))
    op.add_column("users", sa.Column("law_firm", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("bar_council_number", sa.String(length=64), nullable=True))
    op.add_column("users", sa.Column("avatar_url", sa.String(length=1024), nullable=True))
    op.add_column("users", sa.Column("city", sa.String(length=128), nullable=True))
    op.add_column("users", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True))
    op.execute(sa.text("UPDATE users SET updated_at = created_at WHERE updated_at IS NULL"))
    with op.batch_alter_table("users") as batch_op:
        batch_op.alter_column(
            "updated_at", existing_type=sa.DateTime(timezone=True), nullable=False
        )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    op.drop_column("users", "city")
    op.drop_column("users", "avatar_url")
    op.drop_column("users", "bar_council_number")
    op.drop_column("users", "law_firm")
    op.drop_column("users", "phone_number")
    op.drop_column("users", "full_name")
    # ### end Alembic commands ###
