import type { Matter, MatterFilters, StageBucket } from "../types/workspace";

export const SEED_MATTERS: Matter[] = [
  {
    id: "arora-meridian",
    name: "Arora v. Meridian Estates Pvt. Ltd.",
    caseNumber: "ARB.P. 428/2026",
    court: "Delhi High Court · Courtroom 18",
    stage: "Interim application",
    practiceArea: "Arbitration",
    lastActivity: "Updated today",
    updatedAt: 18,
    petitioner: "R.K. Arora",
    respondent: "Meridian Estates Pvt. Ltd.",
    matterType: "Arbitration",
    createdDate: "18 Jul 2025",
    health: "Needs attention",
    discrepanciesCount: 3,
    citationsCount: 14,
  },
  {
    id: "khanna-trademark",
    name: "Khanna Labs — Trademark Opposition",
    caseNumber: "TM-O 88/2026",
    court: "Trademark Registry, Delhi",
    stage: "Drafting",
    practiceArea: "Intellectual Property",
    lastActivity: "Updated today",
    updatedAt: 17,
    petitioner: "Khanna Labs Pvt. Ltd.",
    respondent: "Zenta Pharmaceuticals Ltd.",
    matterType: "Intellectual Property",
    createdDate: "14 May 2026",
    health: "Healthy",
    discrepanciesCount: 0,
    citationsCount: 8,
  },
  {
    id: "gupta-zenith",
    name: "Gupta v. Zenith Developers Ltd.",
    caseNumber: "CS(COMM) 319/2026",
    court: "Delhi High Court · Commercial Division",
    stage: "Notice issued",
    practiceArea: "Commercial",
    lastActivity: "Updated 2 days ago",
    updatedAt: 16,
    petitioner: "Sanjay Gupta",
    respondent: "Zenith Developers Ltd.",
    matterType: "Commercial",
    createdDate: "05 Sept 2026",
    health: "Healthy",
    discrepanciesCount: 0,
    citationsCount: 12,
  },
  {
    id: "sharma-union",
    name: "Sharma v. Union of India",
    caseNumber: "W.P.(C) 1147/2026",
    court: "Supreme Court of India",
    stage: "Notice issued",
    practiceArea: "Civil · Writ",
    lastActivity: "Updated yesterday",
    updatedAt: 15,
    petitioner: "Vikram Sharma",
    respondent: "Union of India",
    matterType: "Civil",
    createdDate: "09 Feb 2026",
    health: "Healthy",
    discrepanciesCount: 0,
    citationsCount: 22,
  },
  {
    id: "oberoi-divorce",
    name: "Oberoi v. Oberoi — Divorce Petition",
    caseNumber: "HMA 301/2026",
    court: "Family Court, Saket",
    stage: "Notice issued",
    practiceArea: "Family",
    lastActivity: "Updated yesterday",
    updatedAt: 14,
    petitioner: "Neha Oberoi",
    respondent: "Karan Oberoi",
    matterType: "Family",
    createdDate: "24 May 2026",
    health: "High risk",
    discrepanciesCount: 4,
    citationsCount: 5,
  },
  {
    id: "iyer-novatek",
    name: "Iyer v. Novatek Systems",
    caseNumber: "ARB 102/2026",
    court: "Arbitration Tribunal · Mumbai",
    stage: "Interim application",
    practiceArea: "Arbitration",
    lastActivity: "Updated 3 days ago",
    updatedAt: 13,
    petitioner: "K.V. Iyer",
    respondent: "Novatek Systems Pvt. Ltd.",
    matterType: "Arbitration",
    createdDate: "29 Aug 2026",
    health: "Needs attention",
    discrepanciesCount: 2,
    citationsCount: 9,
  },
  {
    id: "mehta-industries",
    name: "Mehta Industries — Contract Review",
    caseNumber: "CR/2026/0098",
    court: "Commercial · Arbitration cell",
    stage: "Drafting",
    practiceArea: "Commercial · Contract",
    lastActivity: "Updated 2 days ago",
    updatedAt: 12,
    petitioner: "Mehta Industries Pvt. Ltd.",
    respondent: "Skyline Logistics Pvt. Ltd.",
    matterType: "Commercial",
    createdDate: "13 Feb 2026",
    health: "High risk",
    discrepanciesCount: 5,
    citationsCount: 7,
  },
  {
    id: "reddy-shareholder",
    name: "Reddy Holdings — Shareholder Dispute",
    caseNumber: "CP 67/2026",
    court: "NCLT, Delhi Bench",
    stage: "Interim application",
    practiceArea: "Corporate",
    lastActivity: "Updated 2 days ago",
    updatedAt: 11,
    petitioner: "V. Reddy Holdings Pvt. Ltd.",
    respondent: "Ananya Reddy",
    matterType: "Corporate",
    createdDate: "04 Apr 2026",
    health: "High risk",
    discrepanciesCount: 6,
    citationsCount: 16,
  },
  {
    id: "chawla-nortech",
    name: "Chawla v. NorTech Solutions Pvt. Ltd.",
    caseNumber: "CS(COMM) 512/2026",
    court: "Delhi High Court · Commercial Division",
    stage: "Filed",
    practiceArea: "Commercial · Contract",
    lastActivity: "Updated 3 days ago",
    updatedAt: 10,
    petitioner: "Rohan Chawla",
    respondent: "NorTech Solutions Pvt. Ltd.",
    matterType: "Commercial",
    createdDate: "07 Jun 2026",
    health: "High risk",
    discrepanciesCount: 4,
    citationsCount: 11,
  },
  {
    id: "kapoor-royal",
    name: "Kapoor v. Royal Habitat Group",
    caseNumber: "RERA/D/2026/412",
    court: "Haryana RERA Tribunal",
    stage: "Filed",
    practiceArea: "Property",
    lastActivity: "Updated 4 days ago",
    updatedAt: 9,
    petitioner: "A.K. Kapoor",
    respondent: "Royal Habitat Realcon Pvt. Ltd.",
    matterType: "Property",
    createdDate: "22 Aug 2026",
    health: "High risk",
    discrepanciesCount: 3,
    citationsCount: 6,
  },
  {
    id: "state-verma",
    name: "State v. Verma",
    caseNumber: "CC 219/2026",
    court: "Sessions Court · Tis Hazari",
    stage: "Evidence",
    practiceArea: "Criminal",
    lastActivity: "Updated 4 days ago",
    updatedAt: 8,
    petitioner: "State of NCT of Delhi",
    respondent: "Ashok Verma",
    matterType: "Criminal",
    createdDate: "04 May 2026",
    health: "Healthy",
    discrepanciesCount: 0,
    citationsCount: 15,
  },
  {
    id: "bansal-trust",
    name: "Bansal Family Trust — Succession",
    caseNumber: "T.S. 77/2026",
    court: "District Court · Saket",
    stage: "Filed",
    practiceArea: "Family · Succession",
    lastActivity: "Updated last week",
    updatedAt: 7,
    petitioner: "Anil Bansal (Legal Heir)",
    respondent: "Deepak Bansal (Contesting Heir)",
    matterType: "Family",
    createdDate: "05 Jul 2026",
    health: "Healthy",
    discrepanciesCount: 0,
    citationsCount: 4,
  },
  {
    id: "kaur-estate",
    name: "Kaur Estate Matter",
    caseNumber: "O.S. 214/2025",
    court: "District Court · Rohini",
    stage: "Evidence",
    practiceArea: "Property",
    lastActivity: "Updated 5 days ago",
    updatedAt: 6,
    petitioner: "Simran Kaur",
    respondent: "Rohini Municipal Corporation",
    matterType: "Property",
    createdDate: "14 Nov 2025",
    health: "Needs attention",
    discrepanciesCount: 2,
    citationsCount: 8,
  },
  {
    id: "singhal-gst",
    name: "Singhal Textiles — GST Appeal",
    caseNumber: "GSTA 44/2026",
    court: "Appellate Tribunal, Delhi",
    stage: "Arguments",
    practiceArea: "Tax",
    lastActivity: "Updated 6 days ago",
    updatedAt: 5,
    petitioner: "Singhal Textiles Pvt. Ltd.",
    respondent: "Commissioner of GST, Delhi",
    matterType: "Tax",
    createdDate: "15 Jul 2026",
    health: "Needs attention",
    discrepanciesCount: 1,
    citationsCount: 10,
  },
  {
    id: "malhotra-dda",
    name: "Malhotra Family Trust v. DDA — Land Acquisition",
    caseNumber: "W.P.(C) 902/2025",
    court: "Delhi High Court",
    stage: "Arguments",
    practiceArea: "Property",
    lastActivity: "Updated 1 week ago",
    updatedAt: 4,
    petitioner: "Malhotra Family Trust",
    respondent: "Delhi Development Authority",
    matterType: "Property",
    createdDate: "01 Mar 2025",
    health: "Healthy",
    discrepanciesCount: 0,
    citationsCount: 13,
  },
  {
    id: "pooja-ramesh",
    name: "Pooja Ramesh Singh v. J&K Bank Ltd.",
    caseNumber: "CP(IB) 819/2026",
    court: "Supreme Court of India · Landmark Precedent",
    stage: "Pre-filing review",
    practiceArea: "Commercial",
    lastActivity: "Updated today",
    updatedAt: 3,
    petitioner: "Pooja Ramesh Singh",
    respondent: "J&K Bank Ltd.",
    matterType: "Commercial",
    createdDate: "10 Jul 2026",
    health: "Needs attention",
    discrepanciesCount: 2,
    citationsCount: 19,
  },
  {
    id: "zenith-corp",
    name: "Zenith Corp v. Registrar of Companies",
    caseNumber: "CO.PET. 42/2026",
    court: "Delhi High Court · Company Court",
    stage: "Notice issued",
    practiceArea: "Corporate",
    lastActivity: "Updated 1 week ago",
    updatedAt: 2,
    petitioner: "Zenith Global Logistics Ltd.",
    respondent: "Registrar of Companies, NCT of Delhi",
    matterType: "Corporate",
    createdDate: "12 Aug 2026",
    health: "Healthy",
    discrepanciesCount: 0,
    citationsCount: 6,
  },
  {
    id: "national-highway",
    name: "National Highway Authority v. Patel Infra",
    caseNumber: "ARB.O.M.P. 182/2026",
    court: "Delhi High Court · Commercial Division",
    stage: "Evidence",
    practiceArea: "Arbitration",
    lastActivity: "Updated 2 weeks ago",
    updatedAt: 1,
    petitioner: "National Highways Authority of India",
    respondent: "Patel Infrastructure Ltd.",
    matterType: "Arbitration",
    createdDate: "19 May 2026",
    health: "High risk",
    discrepanciesCount: 7,
    citationsCount: 24,
  },
];

export const EMPTY_FILTERS: MatterFilters = {
  types: [],
  stages: [],
  statuses: [],
};

export function classifyStage(stage: string): StageBucket {
  const value = stage.toLowerCase();
  if (value.includes("draft") || value.includes("review")) return "drafting";
  if (
    ["disposed", "concluded", "closed", "decree"].some((word) =>
      value.includes(word),
    )
  ) {
    return "final";
  }
  if (
    ["filed", "notice issued", "admitted"].some((word) => value.includes(word))
  ) {
    return "initiation";
  }
  return "progress";
}
